#!/usr/bin/env bash
set -euo pipefail

URL="https://rhadp-aib-cdn.s3.us-east-2.amazonaws.com/prebuilt/auto-osbuild-qemu-autosd9-qa-regular-aarch64-1783130066.5c504f6e.qcow2"

echo "Flashing image ${URL}"
set -x
j flasher flash "${URL}"
