#!/usr/bin/env bash
set -euxo pipefail

REV=$(git rev-parse HEAD)
URL="https://rhadp-aib-cdn.s3.us-east-2.amazonaws.com/${{ values.owner }}-${{ values.component_id }}/${REV}_autosd9-qemu.qcow2"

echo "Flashing image ${URL}"
j flasher flash "${URL}"
