name: Build container images
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
jobs:
  build-image:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            name: devspace
          - runs-on: ubuntu-24.04-arm
            name: exporter
          - runs-on: ubuntu-24.04-arm
            name: application
          - runs-on: ubuntu-latest
            name: che-code
    runs-on: ${{ matrix.runs-on }}
    permissions:
      packages: write
      contents: read
    steps:
      - uses: docker/login-action@v3
        with:
          registry: quay.io
          username: jumpstarter-dev+summit_ci
          password: ${{ secrets.QUAY_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: quay.io/jumpstarter-dev/summit-${{ matrix.name }}
      - uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:containers/${{ matrix.name }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
